Document: spirv-headers
Title: Debian spirv-headers Manual
Author: <insert document author here>
Abstract: This manual describes what spirv-headers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spirv-headers/spirv-headers.sgml.gz

Format: postscript
Files: /usr/share/doc/spirv-headers/spirv-headers.ps.gz

Format: text
Files: /usr/share/doc/spirv-headers/spirv-headers.text.gz

Format: HTML
Index: /usr/share/doc/spirv-headers/html/index.html
Files: /usr/share/doc/spirv-headers/html/*.html
