name: build-ubuntu-packages
run-name: Build Debian style packages for Ubuntu distros
on:
  push:
  workflow_call:
    inputs:
      spirv_headers:
        required: true
        type: string
        default: '{"repo":"johnzupin/SPIRV-Headers","ref":"ubuntu/focal"}'
        description: "A json string that defines repo and ref. Ex) {repo:johnzupin/SPIRV-Headers, ref:ubuntu/focal}"
  workflow_dispatch:
    inputs:
      spirv_headers:
        required: true
        type: string
        default: '{"repo":"johnzupin/SPIRV-Headers","ref":"ubuntu/focal"}'
        description: "A json string that defines repo and ref. Ex) {repo:johnzupin/SPIRV-Headers, ref:ubuntu/focal}"

jobs:
  build-spirv-headers-focal-package:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Repo and Ref with no inputs specified"
        if: ${{ inputs.spirv_headers == '' }}
        run: |
          echo "Inputs not specified - Running as a push event"
          echo "SPIRV_REPO=$GITHUB_REPOSITORY" >> "$GITHUB_ENV"
          echo "SPIRV_REF=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
      - name: "Set Repo and Ref with inputs specified"
        if: ${{ inputs.spirv_headers != '' }}
        run: |
          echo "Input has been specified - Running a reusable or dispatch call"
          echo "Using specified repo/ref from input: ${{ inputs.spirv_repo }}"
          echo "SPIRV_REPO=${{ fromJSON(inputs.spirv_headers).repo }}" >> "$GITHUB_ENV"
          echo "SPIRV_REF=${{ fromJSON(inputs.spirv_headers).ref }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-spirv-headers-package
        with:
          repo: "${{ env.SPIRV_REPO }}"
          ref: "${{ env.SPIRV_REF }}"
      - uses: actions/upload-artifact@v3
        with:
          name: "spirv-headers-focal-package"
          path: "${{ runner.temp }}/_github_home/spirv-headers*20.04*_all.deb"
          if-no-files-found: error
